development:
  adapter: postgresql
  encoding: unicode
  database: sendasong_development
  pool: 5
  username: sendasong
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: sendasong_test
  pool: 5
  username: sendasong
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: sendasong_production
  pool: 5
  username: sendasong
  password:

